### ISSUE TITLE
how to get the 7 cytoarchitectonic classes of the von Economo atlas

### ISSUE THREAD

**Issue by sunlianglong** [frantisekvasa/structural_network_development#1]
Hi～
Now I only get this information from the paper: _An MRI Von Economo – Koskinas atlas_ , but i do not know how to get the 7 cytoarchitectonic classes of  the von Economo atlas, just like you did in this interesting paper!  could you tell me how to do it, or how to get extra infomation?  Thank you!!
![image](https://user-images.githubusercontent.com/16713005/86576390-4370cc00-bfab-11ea-8f54-5daa08c0ff16.png)

**Comment by frantisekvasa** [comment]
Hi,
The mapping of cortical ROIs to von Economo cytoarchitectonic classes was originally performed by my colleagues, as described here https://royalsocietypublishing.org/doi/10.1098/rstb.2015.0362#d3e722 (section "(d) Parcellation into cytoarchitectonic classes").
The labels for the 308 cortical ROIs used for analysis in the study related to this repository are available with the remainder of the data here: https://www.repository.cam.ac.uk/handle/1810/263627 - however, access to this data has to be requested. 
Alternatively, the same labels were used as part of another study, and are available here: https://github.com/SarahMorgan/Morphometric_Similarity_SZ (file "vonEcon_500_overlap.txt")
Finally, this study https://www.pnas.org/content/117/6/3248 used the same cytorachitectonic classes, but as mapped to the 360-ROI multi-modal parcellation by Glasser et al - these labels are available here https://figshare.com/articles/Data_for_Conservative_and_disruptive_modes_of_adolescent_change_in_human_brain_functional_connectivity_/11551602 (variable "ve.id.subc" in the file "nspn.fmri.general.vars.RData" - where the first 16 values correspond to subcortical regions, labeled as "8", and the remaining 360 values to the crotical ROIs of the Glasser et al atlas).
As a final note, these classes are different from the ones in the paper "An MRI Von Economo – Koskinas atlas".
I hope this helps!
Frantisek

**Comment by sunlianglong** [comment]
This helped me. Thank you for your detailed answer!
Next, I want to read your very interesting articles carefully, thank you for sharing.

Lianglong Sun
